# Generated by Django 5.2.11 on 2026-03-29 22:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AProposPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Contenu"),
                ),
            ],
            options={
                "verbose_name": "À Propos",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FAQPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "categories",
                    wagtail.fields.StreamField(
                        [("category", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre de la catégorie"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Question"}),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Réponse"},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 1), ("answer", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (3,),
                                {"label": "Questions"},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("questions", 4)]],
                                {},
                            ),
                        },
                        verbose_name="Catégories",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Monde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Description"
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte du CTA"
                    ),
                ),
                ("cta_link", models.URLField(blank=True, verbose_name="Lien du CTA")),
            ],
            options={
                "verbose_name": "Monde",
                "verbose_name_plural": "Mondes",
            },
        ),
        migrations.CreateModel(
            name="ProgrammationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "tabs",
                    wagtail.fields.StreamField(
                        [("tab", 9)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre du tab"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                            2: ("wagtail.blocks.DateBlock", (), {"label": "Date"}),
                            3: ("wagtail.blocks.TimeBlock", (), {"label": "Heure"}),
                            4: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            5: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("core.Guest",),
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {"label": "Invités", "min_num": 0},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("date", 2),
                                        ("start_time", 3),
                                        ("description", 4),
                                        ("guests", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.ListBlock",
                                (7,),
                                {"label": "Animations"},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("animations", 8)]],
                                {},
                            ),
                        },
                        verbose_name="Tabs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programmation",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "press_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Document Presse & Pro",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
            },
        ),
        migrations.CreateModel(
            name="FooterPageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
                (
                    "footer",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_page_links",
                        to="core.footersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Description"
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invité",
                "verbose_name_plural": "Invités",
            },
        ),
        migrations.CreateModel(
            name="HeaderSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header",
            },
        ),
        migrations.CreateModel(
            name="HeaderNavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="URL externe"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
                (
                    "header",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_links",
                        to="core.headersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter / X"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("discord", "Discord"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de plateforme",
                    ),
                ),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Icône",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien social media",
                "verbose_name_plural": "Liens social media",
            },
        ),
        migrations.CreateModel(
            name="FooterSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "footer",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_social_links",
                        to="core.footersettings",
                    ),
                ),
                (
                    "social_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.socialmedialink",
                        verbose_name="Lien social media",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
