# Generated by Django 5.2.11 on 2026-04-05 19:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='navbar',
            field=wagtail.fields.StreamField([('navbar', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du lien'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Lien'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Ouvrir dans un nouvel onglet?', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('open_in_new_tab', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Liens gauche nav', 'required': False}), 5: ('wagtail.blocks.ListBlock', (3,), {'label': 'Liens droite nav', 'required': False}), 6: ('wagtail.blocks.ListBlock', (3,), {'label': 'Liens en haut du menu lateral', 'required': False}), 7: ('wagtail.blocks.ListBlock', (3,), {'label': 'Liens en bas du menu lateral', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('top_links', 6), ('bottom_links', 7)]], {'label': 'Menu lateral', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('links_left', 4), ('links_right', 5), ('drawer_menu', 8)]], {})}, help_text='Configuration editable de la navigation principale', verbose_name='Navigation'),
        ),
    ]
