# Generated by Django 5.2.11 on 2026-04-11 11:12

import json

import wagtail.fields
from django.db import migrations


def convert_apropos_content_to_streamfield(apps, schema_editor):
    AProposPage = apps.get_model("core", "AProposPage")

    for page in AProposPage.objects.all():
        old_content = (page.content or "").strip()

        if old_content:
            page.content = json.dumps(
                [
                    {
                        "type": "category",
                        "value": {
                            "title": "Contenu",
                            "content": old_content,
                        },
                    }
                ]
            )
        else:
            page.content = json.dumps([])

        page.save(update_fields=["content"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_headernavbarleftlink_headernavbarrightlink_and_more"),
    ]

    operations = [
        migrations.RunPython(
            convert_apropos_content_to_streamfield,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="apropospage",
            name="content",
            field=wagtail.fields.StreamField(
                [("category", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titre de la catégorie"},
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Contenu", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                },
                verbose_name="Contenu",
            ),
        ),
    ]
