# Generated by Django 5.2.11 on 2026-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_apropospage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform_type",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter / X"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("discord", "Discord"),
                    ("twitch", "Twitch"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
                verbose_name="Type de plateforme",
            ),
        ),
    ]
