# Generated by Django 5.2.11 on 2026-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_headersettings_navbar_headernavbarleftlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headernavbarleftlink',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='headernavbarrightlink',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='headernavmenubottomlink',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='headernavmenutoplink',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
    ]
