# Generated by Django 5.2.11 on 2026-06-25 19:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_socialmedialink_platform_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationpage",
            name="tabs",
            field=wagtail.fields.StreamField(
                [("tab", 10)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Titre du tab"}),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    2: ("wagtail.blocks.DateBlock", (), {"label": "Date"}),
                    3: ("wagtail.blocks.TimeBlock", (), {"label": "Heure de début"}),
                    4: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {"label": "Heure de fin", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    6: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {"label": "Invités", "min_num": 0},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("date", 2),
                                ("start_time", 3),
                                ("end_time", 4),
                                ("description", 5),
                                ("guests", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {"label": "Animations"}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("animations", 9)]],
                        {},
                    ),
                },
                verbose_name="Tabs",
            ),
        ),
    ]
