# Generated by Django 5.2.11 on 2026-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_headernavbarleftlink_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headersettings",
            name="cta_label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Texte du bouton"
            ),
        ),
        migrations.AddField(
            model_name="headersettings",
            name="cta_url",
            field=models.URLField(blank=True, verbose_name="URL du bouton"),
        ),
    ]
