# Generated by Django 5.2.11 on 2026-07-02 19:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_programmationpage_tabs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationpage",
            name="tabs",
            field=wagtail.fields.StreamField(
                [("tab", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Lieu du festival (tables, scènes, stands, etc.)",
                            "label": "Titre du tab",
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page interne", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("home-hero", "Accueil - Hero"),
                                ("home-presentation", "Accueil - Presentation"),
                                ("home-espaces", "Accueil - Espaces"),
                                ("home-espaces-mondes", "Accueil - Espaces mondes"),
                                ("home-guests", "Accueil - Invites"),
                                ("home-info", "Accueil - Infos pratiques"),
                                ("home-ticker", "Accueil - Ticker"),
                                ("home-hero-fomo", "Accueil - Hero FOMO"),
                            ],
                            "help_text": "Optionnel. Utilisé seulement si la page interne choisie est la page d'accueil.",
                            "label": "Section de la page d'accueil",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL externe", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 1), ("section_anchor", 2), ("external_url", 3)]],
                        {
                            "help_text": "Lien à ouvrir dans un nouvel onglet plutôt que d'afficher les animations de cette catégorie (ex: lien vers l'inscription aux tables)",
                            "label": "Lien",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    6: ("wagtail.blocks.DateBlock", (), {"label": "Date"}),
                    7: ("wagtail.blocks.TimeBlock", (), {"label": "Heure de début"}),
                    8: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {"label": "Heure de fin", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    10: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"label": "Invités", "min_num": 0},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("date", 6),
                                ("start_time", 7),
                                ("end_time", 8),
                                ("description", 9),
                                ("guests", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {"label": "Animations"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 4), ("animations", 13)]],
                        {},
                    ),
                },
                verbose_name="Tabs",
            ),
        ),
    ]
