# Generated by Django 5.2.11 on 2026-04-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_headersettings_cta_color_headersettings_cta_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='cta_label',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='cta_url',
        ),
    ]
