# Generated by Django 5.2.11 on 2026-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_programmationpage_tabs"),
    ]

    operations = [
        migrations.AddField(
            model_name="headernavbarleftlink",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="headernavbarrightlink",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="headernavmenubottomlink",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="headernavmenutoplink",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
    ]
