# Generated by Django 5.2.11 on 2026-07-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_headernavbarleftlink_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Monde",
            new_name="Espace",
        ),
        migrations.AlterModelOptions(
            name="espace",
            options={"verbose_name": "Espace", "verbose_name_plural": "Espaces"},
        ),
        migrations.RemoveField(
            model_name="headersettings",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="socialmedialink",
            name="icon",
        ),
    ]
