# Generated by Django 5.2.11 on 2026-09-11 14:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_programmationpage_tabs"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerpagelink",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="footerpagelink",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="URL Externe"),
        ),
        migrations.AlterField(
            model_name="programmationpage",
            name="tabs",
            field=wagtail.fields.StreamField(
                [("tab", 15)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Lieu du festival (tables, scènes, stands, etc.)",
                            "label": "Titre du tab",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Un sous titre à afficher dans le tab",
                            "label": "Sous-titre",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page interne", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("home-hero", "Accueil - Hero"),
                                ("home-presentation", "Accueil - Presentation"),
                                ("home-espaces", "Accueil - Espaces"),
                                ("home-espaces-mondes", "Accueil - Espaces mondes"),
                                ("home-guests", "Accueil - Invites"),
                                ("home-info", "Accueil - Infos pratiques"),
                                ("home-ticker", "Accueil - Ticker"),
                                ("home-hero-fomo", "Accueil - Hero FOMO"),
                            ],
                            "help_text": "Optionnel. Utilisé seulement si la page interne choisie est la page d'accueil.",
                            "label": "Section de la page d'accueil",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL externe", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 2), ("section_anchor", 3), ("external_url", 4)]],
                        {
                            "help_text": "Lien à ouvrir dans un nouvel onglet plutôt que d'afficher les animations de cette catégorie (ex: lien vers l'inscription aux tables)",
                            "label": "Lien",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    7: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"label": "Date", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {"label": "Heure de début", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.TimeBlock",
                        (),
                        {"label": "Heure de fin", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    11: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {"label": "Invités", "min_num": 0},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 6),
                                ("date", 7),
                                ("start_time", 8),
                                ("end_time", 9),
                                ("description", 10),
                                ("guests", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {"label": "Animations"}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("link", 5),
                                ("animations", 14),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Tabs",
            ),
        ),
    ]
