# Generated by Django 5.2.11 on 2026-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_footerpagelink_email_footerpagelink_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="url",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
    ]
