# Generated by Django 5.2.11 on 2026-03-29 22:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_prepare_body_for_streamfield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Page d'accueil"},
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 4),
                    ("espaces", 7),
                    ("guests", 10),
                    ("info", 13),
                    ("ticker", 16),
                    ("hero_fomo", 20),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sous-titre", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Tagline", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Lien billetterie", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("tagline", 2),
                                ("ticket_url", 3),
                            ]
                        ],
                        {},
                    ),
                    5: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Monde",),
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {"label": "Mondes"}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("mondes", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {"label": "Invités"}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("guests", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Accès", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Horaires", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("access", 11), ("schedule", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"label": "Texte"}),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {"label": "Textes défilants"},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("texts", 15)]], {}),
                    17: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.SocialMediaLink",),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Liens social media"},
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Lien Discord", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("social_links", 18), ("discord_url", 19)]],
                        {},
                    ),
                },
                verbose_name="Sections",
            ),
        ),
    ]
