# Generated by Django 5.2.11 on 2026-04-01 19:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 9), ('espaces', 12), ('guests', 15), ('info', 18), ('ticker', 21), ('hero_fomo', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Tagline', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Lien billetterie', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Billetterie', 'label': 'Texte du bouton'}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Lien', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')], 'label': 'Variant'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('purple', 'Purple'), ('green', 'Green')], 'help_text': 'Utilise avec le variant secondary.', 'label': 'Couleur', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('variant', 6), ('color', 7)]], {'label': 'CTA', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('tagline', 2), ('ticket_url', 3), ('cta', 8)]], {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Monde',), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Mondes'}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('mondes', 11)]], {}), 13: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Guest',), {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Invités'}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('guests', 14)]], {}), 16: ('wagtail.blocks.RichTextBlock', (), {'label': 'Accès', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Horaires', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 0), ('access', 16), ('schedule', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Textes défilants'}), 21: ('wagtail.blocks.StructBlock', [[('texts', 20)]], {}), 22: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.SocialMediaLink',), {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Liens social media'}), 24: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Discord', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 0), ('social_links', 23), ('discord_url', 24)]], {})}, verbose_name='Sections'),
        ),
    ]
