# Generated by Django 5.2.11 on 2026-04-07 19:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_options_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('presentation', 10), ('espaces', 13), ('guests', 20), ('info', 23), ('ticker', 26), ('hero_fomo', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Tagline', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Lien billetterie', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Lien à propos', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': "...Mais avant, qu'est-ce que c'est ?", 'label': 'Texte du lien à propos', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('tagline', 2), ('ticket_url', 3), ('about_url', 4), ('text_about_url', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Texte de la carte'}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Cartes', 'max_num': 5}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7), ('cards', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Monde',), {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Mondes'}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('mondes', 12)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Guest',), {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Invités'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Et bien plus encore...', 'label': "Texte d'accroche", 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Voir le programme', 'label': 'Texte du bouton'}), 18: ('wagtail.blocks.URLBlock', (), {'label': 'Lien du bouton'}), 19: ('wagtail.blocks.StructBlock', [[('label', 17), ('url', 18)]], {'label': 'Call to action', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 0), ('guests', 15), ('teaser_text', 16), ('cta', 19)]], {}), 21: ('wagtail.blocks.RichTextBlock', (), {'label': 'Accès', 'required': False}), 22: ('wagtail.blocks.RichTextBlock', (), {'label': 'Horaires', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 0), ('access', 21), ('schedule', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 25: ('wagtail.blocks.ListBlock', (24,), {'label': 'Textes défilants'}), 26: ('wagtail.blocks.StructBlock', [[('texts', 25)]], {}), 27: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.SocialMediaLink',), {}), 28: ('wagtail.blocks.ListBlock', (27,), {'label': 'Liens social media'}), 29: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Discord', 'required': False}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'WWyrd - Festival de jeu de rôle immersif - Cité Fertile, Pantin - 11 octobre 2026', 'label': "Texte d'accroche", 'required': False}), 31: ('wagtail.blocks.StructBlock', [[('title', 0), ('social_links', 28), ('discord_url', 29), ('ticket_url', 3), ('about_text', 30)]], {})}, verbose_name='Sections'),
        ),
    ]
