# Generated by Django 5.2.11 on 2026-04-03 21:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('espaces', 9), ('guests', 12), ('info', 15), ('ticker', 18), ('hero_fomo', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Tagline', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Lien billetterie', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Lien à propos', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': "...Mais avant, qu'est-ce que c'est ?", 'label': 'Texte du lien à propos', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('tagline', 2), ('ticket_url', 3), ('about_url', 4), ('text_about_url', 5)]], {}), 7: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Monde',), {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Mondes'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('mondes', 8)]], {}), 10: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Guest',), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Invités'}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('guests', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'label': 'Accès', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'label': 'Horaires', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('access', 13), ('schedule', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Textes défilants'}), 18: ('wagtail.blocks.StructBlock', [[('texts', 17)]], {}), 19: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.SocialMediaLink',), {}), 20: ('wagtail.blocks.ListBlock', (19,), {'label': 'Liens social media'}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Discord', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 0), ('social_links', 20), ('discord_url', 21)]], {})}, verbose_name='Sections'),
        ),
    ]
