# Generated by Django 5.2.11 on 2026-04-06 11:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('presentation', 10), ('espaces', 13), ('guests', 16), ('info', 19), ('ticker', 22), ('hero_fomo', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Tagline', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Lien billetterie', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Lien à propos', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': "...Mais avant, qu'est-ce que c'est ?", 'label': 'Texte du lien à propos', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('tagline', 2), ('ticket_url', 3), ('about_url', 4), ('text_about_url', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Texte de la carte'}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Cartes', 'max_num': 5}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 7), ('cards', 9)]], {}), 11: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Monde',), {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Mondes'}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('mondes', 12)]], {}), 14: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.Guest',), {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Invités'}), 16: ('wagtail.blocks.StructBlock', [[('title', 0), ('guests', 15)]], {}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Accès', 'required': False}), 18: ('wagtail.blocks.RichTextBlock', (), {'label': 'Horaires', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('access', 17), ('schedule', 18)]], {}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Texte'}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Textes défilants'}), 22: ('wagtail.blocks.StructBlock', [[('texts', 21)]], {}), 23: ('wagtail.snippets.blocks.SnippetChooserBlock', ('core.SocialMediaLink',), {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Liens social media'}), 25: ('wagtail.blocks.URLBlock', (), {'label': 'Lien Discord', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('title', 0), ('social_links', 24), ('discord_url', 25)]], {})}, verbose_name='Sections'),
        ),
    ]
