# Generated by Django 5.2.11 on 2026-06-25 19:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("landing_page", 7),
                    ("hero", 16),
                    ("presentation", 20),
                    ("espaces", 25),
                    ("guests", 32),
                    ("info", 37),
                    ("ticker", 39),
                    ("hero_fomo", 44),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Incarne l'histoire",
                            "label": "Titre",
                            "placeholder": "Incarne l'histoire",
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "L'histoire s'écrit. Le site aussi.\nEn attendant, la suite est par ici...",
                            "label": "Sous-titre",
                            "placeholder": "L'histoire s'écrit. Le site aussi.\nEn attendant, la suite est par ici...",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cité Fertile - Pantin - 11 oct. 2026",
                            "label": "Tagline",
                            "placeholder": "Cité Fertile - Pantin - 11 oct. 2026",
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.helloasso.com/associations/wyrd/evenements/billetterie-wyrd-2026",
                            "label": "Lien billetterie",
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.instagram.com/wyrd.folks/",
                            "label": "Lien Instagram",
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Texte"}),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "default": ["zero prerequis", "observe", "joue en famille"],
                            "label": "Textes défilants",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("tagline", 2),
                                ("ticket_url", 3),
                                ("instagram_url", 4),
                                ("ticker_text", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sous-titre", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Tagline", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page interne", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL externe", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien billetterie", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien à propos", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "...Mais avant, qu'est-ce que c'est ?",
                            "label": "Texte du lien à propos",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("subtitle", 9),
                                ("tagline", 10),
                                ("ticket_url", 13),
                                ("about_url", 14),
                                ("text_about_url", 15),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte de la carte"},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"label": "Cartes", "max_num": 5},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("description", 17), ("cards", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    22: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Monde",),
                        {},
                    ),
                    23: ("wagtail.blocks.ListBlock", (22,), {"label": "Mondes"}),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("intro", 21),
                                ("title", 8),
                                ("subtitle", 9),
                                ("mondes", 23),
                                ("picture", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {"label": "Invités"}),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Et bien plus encore...",
                            "label": "Texte d'accroche",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Voir le programme", "label": "Texte du bouton"},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien du bouton"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 29), ("url", 30)]],
                        {"label": "Call to action", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("guests", 27),
                                ("teaser_text", 28),
                                ("cta", 31),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Accès", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Horaires", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien vers la page d'accès", "required": False},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien vers la FAQ", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("access", 33),
                                ("schedule", 34),
                                ("directions_link", 35),
                                ("faq_link", 36),
                                ("picture", 24),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"label": "Textes défilants"},
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("texts", 38)]], {}),
                    40: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.SocialMediaLink",),
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (40,),
                        {"label": "Liens social media"},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("external_url", 12)]],
                        {"label": "Lien Discord", "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Wyrd - Festival de jeu de rôle immersif - Cité Fertile, Pantin - 11 octobre 2026",
                            "label": "Texte d'accroche",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("social_links", 41),
                                ("discord_url", 42),
                                ("ticket_url", 13),
                                ("about_text", 43),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Sections",
            ),
        ),
    ]
