# Generated by Django 5.2.11 on 2026-09-10 10:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("landing_page", 7),
                    ("hero", 17),
                    ("presentation", 23),
                    ("espaces", 29),
                    ("guests", 37),
                    ("info", 42),
                    ("ticker", 44),
                    ("hero_fomo", 49),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Incarne l'histoire",
                            "label": "Titre",
                            "placeholder": "Incarne l'histoire",
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "L'histoire s'écrit. Le site aussi.\nEn attendant, la suite est par ici...",
                            "label": "Sous-titre",
                            "placeholder": "L'histoire s'écrit. Le site aussi.\nEn attendant, la suite est par ici...",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cité Fertile - Pantin - 11 oct. 2026",
                            "label": "Tagline",
                            "placeholder": "Cité Fertile - Pantin - 11 oct. 2026",
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.helloasso.com/associations/wyrd/evenements/billetterie-wyrd-2026",
                            "label": "Lien billetterie",
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://www.instagram.com/wyrd.folks/",
                            "label": "Lien Instagram",
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Texte"}),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {
                            "default": ["zero prerequis", "observe", "joue en famille"],
                            "label": "Textes défilants",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("tagline", 2),
                                ("ticket_url", 3),
                                ("instagram_url", 4),
                                ("ticker_text", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"label": "Titre"}),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Sous-titre", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Tagline", "required": False},
                    ),
                    11: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page interne", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("home-hero", "Accueil - Hero"),
                                ("home-presentation", "Accueil - Presentation"),
                                ("home-espaces", "Accueil - Espaces"),
                                ("home-espaces-mondes", "Accueil - Espaces mondes"),
                                ("home-guests", "Accueil - Invites"),
                                ("home-info", "Accueil - Infos pratiques"),
                                ("home-ticker", "Accueil - Ticker"),
                                ("home-hero-fomo", "Accueil - Hero FOMO"),
                            ],
                            "help_text": "Optionnel. Utilisé seulement si la page interne choisie est la page d'accueil.",
                            "label": "Section de la page d'accueil",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL externe", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien billetterie", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien à propos", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "...Mais avant, qu'est-ce que c'est ?",
                            "label": "Texte du lien à propos",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("subtitle", 9),
                                ("tagline", 10),
                                ("ticket_url", 14),
                                ("about_url", 15),
                                ("text_about_url", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Texte de la carte"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 19), ("link", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (21,),
                        {"label": "Cartes", "max_num": 5},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("description", 18), ("cards", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Introduction", "required": False},
                    ),
                    25: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Espace",),
                        {},
                    ),
                    26: ("wagtail.blocks.ListBlock", (25,), {"label": "Mondes"}),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien de l'image", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("intro", 24),
                                ("title", 8),
                                ("subtitle", 9),
                                ("mondes", 26),
                                ("picture", 27),
                                ("pictureLink", 28),
                            ]
                        ],
                        {},
                    ),
                    30: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.Guest",),
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {"label": "Invités"}),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Et bien plus encore...",
                            "label": "Texte d'accroche",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ListBlock",
                        (30,),
                        {"label": "Autre invitées"},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Voir le programme", "label": "Texte du bouton"},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien du bouton"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 34), ("url", 35)]],
                        {"label": "Call to action", "required": False},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("guests", 31),
                                ("teaser_text", 32),
                                ("secondary_guests", 33),
                                ("cta", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Accès", "required": False},
                    ),
                    39: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "Horaires", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien vers la page d'accès", "required": False},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien vers la FAQ", "required": False},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("access", 38),
                                ("schedule", 39),
                                ("directions_link", 40),
                                ("faq_link", 41),
                                ("picture", 27),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"label": "Textes défilants"},
                    ),
                    44: ("wagtail.blocks.StructBlock", [[("texts", 43)]], {}),
                    45: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.SocialMediaLink",),
                        {},
                    ),
                    46: (
                        "wagtail.blocks.ListBlock",
                        (45,),
                        {"label": "Liens social media"},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 11), ("section_anchor", 12), ("external_url", 13)]],
                        {"label": "Lien Discord", "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Wyrd - Festival de jeu de rôle immersif - Cité Fertile, Pantin - 11 octobre 2026",
                            "label": "Texte d'accroche",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 8),
                                ("social_links", 46),
                                ("discord_url", 47),
                                ("ticket_url", 14),
                                ("about_text", 48),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Sections",
            ),
        ),
    ]
