name: Deploy

on:
  push:
    branches:
      - main
      - ben/deployV2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Fabric
        run: |
          pip install fabric==3.2.2
          pip install requests

      - name: Deploy
        env:
          WFS_API_KEY: ${{ secrets.WFS_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.HOST }}
          DEPLOY_USER: ${{ secrets.USER }}
          DEPLOY_ACCOUNT: ${{ secrets.ACCOUNT }}
          DEPLOY_SITE_ID: ${{ github.ref_name == 'main' && secrets.PROD_SITE_ID || secrets.DEV_SITE_ID  }}
          DEPLOY_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
        run: fab deploy
